### ISSUE TITLE
SAP HANA Cloud Deployment via MTA?

### ISSUE THREAD

**Issue by gregorwolf** [SAP-samples/hana-enterprise-search-engine#32]
Will it work / is it planned to provide a SAP HANA Cloud Deployment using MTA?

**Comment by kfuerst** [comment]
Hi Gregor. No, this is currently not planned as our first customer is on-prem. Please feel free to contact me in case you need that and want to contribute it. Best regards, Karl

**Comment by remi-sap** [comment]
Hi Gregor, In addition to the Dockerfile you saw, I could publish the deployment file for Kyma/Kubernetes I'm using.

**Comment by gregorwolf** [comment]
For on prem a deployment to HANA XSA would also work with an MTA.
