### ISSUE TITLE
Does the API support the existing SAPUI5 sap.esh.search.ui.SearchCompositeControl?

### ISSUE THREAD

**Issue by gregorwolf** [SAP-samples/hana-enterprise-search-engine#39]
Hello,

HANA has an embedded functionality called [SAP HANA Search](https://help.sap.com/docs/SAP_HANA_PLATFORM/691cb949c1034198800afde3e5be6570/ce86ef2fd97610149eaaaa0244ca4d36.html?version=2.0.05&locale=en-US) it supports the SAPUI5 control [sap.esh.search.ui.SearchCompositeControl](https://ui5.sap.com/#/api/sap.esh.search.ui.SearchCompositeControl). Is this project compatible?

Best Regards
Gregor

**Comment by gregorwolf** [comment]
OK, seems the answer is here: [Enterprise Search UI](https://sap-samples.github.io/hana-enterprise-search-engine/pages/api.html#enterprise-search-ui)

**Comment by kfuerst** [comment]
Hi Gregor, 

yes, the UI is already used here. It basically consumes the HANA built-in procedure ESH_SEARCH exposed via the v1/search endpoint (see server.py).

Additionally to that, we are currently working on an OpenAPI-compatible endpoint (most likely v1/query) with features like fully dynamic requests/responses. This is new and also work in progress, so there is no standard-UI available.

Best regards,
Karl
